config/routes.rb
SwapzappPrintservice::Application.routes.draw do

  root 'static_pages#home'
  match '/templates', to: 'static_pages#templates', via: 'get'
  match '/printers',  to: 'static_pages#printers',  via: 'get'
  match '/print',     to: 'static_pages#print',     via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def templates
  end

  def printers
  end

  def print
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.infinitetoken.com" target="blank">Infinite Token&reg;</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Swapzapp Print</a>
    </div>
    <!-- Left navbar section -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <!-- Right navbar section -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Printers", printers_path %></li>
        <li><%= link_to "Templates", templates_path %></li>
        <li>
          <%= link_to print_path do %>
            <i class="fa fa-print"></i>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swapzapp Print</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><i class="fa fa-tasks"></i> Print jobs <a class="pull-right btn btn-primary" href="#"><i class="fa fa-plus"></i> New Job</a></h3>
        </div>
        <div class="panel-body jobtable">
          <table class="table">
            <thead>
              <th>Name</th>
              <th>To</th>
              <th>From</th>
              <th>Date</th>
              <th>Completed?</th>
              <th></th>
            </thead>
            <tbody>
              <tr>
                <td>3-INCH SALES RECEIPT</td>
                <td>DT BACK</td>
                <td>STH FRONT</td>
                <td>4/28</td>
                <td>Yes</td>
                <td>
                  <a href="#"><i class="fa fa-eye"></i></a>
                  |
                  <a href="#"><i class="fa fa-print"></i></a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/print.html.erb
<h1>static_pages#print</h1>

app/views/static_pages/printers.html.erb
<h1>static_pages#printers</h1>

app/views/static_pages/templates.html.erb
<h1>static_pages#templates</h1>